- id: addon_elasticsearch_cpu
  name: ElasticSearch实例CPU使用率异常告警
  alert_scope: org
  attributes:
    level: Warning
    recover: "true"
    alert_group: '{{cluster_name}}-{{container_id}}'
    tickets_metric_key: '{{container_id}}'
- id: addon_elasticsearch_mem
  name: Elasticsearch实例内存使用率异常告警
  alert_scope: org
  attributes:
    level: Warning
    recover: "true"
    alert_group: '{{cluster_name}}-{{container_id}}'
    tickets_metric_key: '{{container_id}}'
- id: addon_mysql_cpu
  name: MySQL实例CPU使用率异常告警
  alert_scope: org
  attributes:
    level: Warning
    recover: "true"
    alert_group: '{{cluster_name}}-{{container_id}}'
    tickets_metric_key: '{{container_id}}'
- id: addon_mysql_mem
  name: MySQL实例内存使用率异常告警
  alert_scope: org
  attributes:
    level: Warning
    recover: "true"
    alert_group: '{{cluster_name}}-{{container_id}}'
    tickets_metric_key: '{{container_id}}'
- id: addon_mysql_slave_status
  name: MySQL实例主从同步异常告警
  alert_scope: org
  attributes:
    level: Warning
    recover: "true"
    alert_group: '{{cluster_name}}-{{addon_id}}'
    tickets_metric_key: '{{addon_id}}'
- id: addon_redis_mem
  name: redis实例内存使用率异常告警
  alert_scope: org
  attributes:
    level: Warning
    recover: "true"
    alert_group: '{{cluster_name}}-{{container_id}}'
    tickets_metric_key: '{{container_id}}'
- id: app_browser_ajax_req
  name: Ajax接口访问性能
  alert_scope: micro_service
  attributes:
    alert_group: '{{tk}}-{{req_path}}-{{host}}'
    display_url_id: micro_bi_ajax
    level: Notice
    recover: "false"
- id: app_browser_apdex
  name: 用户体验
  alert_scope: micro_service
  attributes:
    alert_group: '{{tk}}-{{doc_path}}-{{host}}'
    display_url_id: micro_bi_position
    level: Notice
    recover: "false"
- id: app_browser_host_req
  name: 域名访问性能
  alert_scope: micro_service
  attributes:
    alert_group: '{{tk}}-{{host}}'
    display_url_id: micro_bi_domain
    level: Notice
    recover: "false"
- id: app_browser_page_req
  name: 页面访问性能
  alert_scope: micro_service
  attributes:
    alert_group: '{{tk}}-{{doc_path}}-{{host}}'
    display_url_id: micro_bi_page
    level: Notice
    recover: "false"
- id: app_browser_script_error
  name: 脚本错误
  alert_scope: micro_service
  attributes:
    alert_group: '{{tk}}-{{doc_path}}-{{host}}'
    display_url_id: micro_bi_script
    level: Notice
    recover: "false"
- id: app_exception_count
  name: 应用错误次数
  alert_scope: micro_service
  attributes:
    alert_group: '{{terminus_key}}-{{error_id}}'
    display_url_id: micro_error_detail
    level: Warning
    recover: "true"
    tickets_metric_key: '{{error_id}}'
- id: app_resource_container_cpu
  name: 应用实例CPU使用率异常
  alert_scope: micro_service
  attributes:
    alert_group: '{{terminus_key}}-{{container_id}}'
    display_url_id: workbench_runtime
    level: Warning
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: app_resource_container_mem
  name: 应用实例内存使用率异常
  alert_scope: micro_service
  attributes:
    alert_group: '{{terminus_key}}-{{container_id}}'
    display_url_id: workbench_runtime
    level: Warning
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: app_resource_container_oom
  name: 应用实例OOM
  alert_scope: micro_service
  attributes:
    alert_group: '{{terminus_key}}-{{container_id}}'
    display_url_id: workbench_runtime
    level: Fatal
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: app_resource_jvm_gc_count
  name: 应用JVM GC次数
  alert_scope: micro_service
  attributes:
    alert_group: '{{terminus_key}}-{{instance_id}}'
    display_url_id: micro_jvm
    level: Warning
    recover: "true"
    tickets_metric_key: '{{instance_id}}'
- id: app_resource_jvm_gc_time
  name: 应用JVM GC 耗时
  alert_scope: micro_service
  attributes:
    alert_group: '{{terminus_key}}-{{instance_id}}'
    display_url_id: micro_jvm
    level: Warning
    recover: "true"
    tickets_metric_key: '{{instance_id}}'
- id: app_resource_jvm_heap
  name: 应用JVM堆内存
  alert_scope: micro_service
  attributes:
    alert_group: '{{terminus_key}}-{{instance_id}}'
    display_url_id: micro_jvm
    level: Warning
    recover: "true"
    tickets_metric_key: '{{instance_id}}'
- id: app_resource_nodejs_heap
  name: 应用NodeJS堆内存使用率
  alert_scope: micro_service
  attributes:
    alert_group: '{{terminus_key}}-{{instance_id}}'
    display_url_id: micro_nodejs
    level: Warning
    recover: "true"
    tickets_metric_key: '{{instance_id}}'
- id: app_status_browser
  name: 页面内容改变
  alert_scope: micro_service
  attributes:
    alert_group: '{{terminus_key}}-{{metric_id}}'
    display_url_id: micro_status_detail
    level: Notice
    recover: "false"
    tickets_metric_key: '{{metric_id}}'
- id: app_status_code
  name: 主动监控HTTP状态异常
  alert_scope: micro_service
  attributes:
    alert_group: '{{terminus_key}}-{{metric_id}}'
    display_url_id: micro_status_detail
    level: Notice
    recover: "true"
    tickets_metric_key: '{{metric_id}}'
- id: app_transaction_http_path_error
  name: 服务接口HTTP错误率异常
  alert_scope: micro_service
  attributes:
    alert_group: '{{target_terminus_key}}-{{target_runtime_id}}-{{target_service_name}}-{{http_path}}-{{http_method}}'
    display_url_id: micro_si_web
    level: Notice
    recover: "true"
    tickets_metric_key: '{{target_application_id}}'
- id: app_transaction_http_path_rt
  name: 服务接口HTTP慢事务异常
  alert_scope: micro_service
  attributes:
    alert_group: '{{target_terminus_key}}-{{target_runtime_id}}-{{target_service_name}}-{{http_path}}-{{http_method}}'
    display_url_id: micro_si_web
    level: Notice
    recover: "true"
    tickets_metric_key: '{{target_application_id}}'
- id: app_transaction_http_service_error
  name: 服务HTTP错误率异常
  alert_scope: micro_service
  attributes:
    alert_group: '{{target_terminus_key}}-{{target_runtime_id}}-{{target_service_name}}'
    display_url_id: micro_si_web
    level: Notice
    recover: "true"
    tickets_metric_key: '{{target_application_id}}'
- id: app_transaction_http_service_rt
  name: 服务HTTP慢事务异常
  alert_scope: micro_service
  attributes:
    alert_group: '{{target_terminus_key}}-{{target_runtime_id}}-{{target_service_name}}'
    display_url_id: micro_si_web
    level: Notice
    recover: "true"
    tickets_metric_key: '{{target_application_id}}'
- id: slave_dly_alert
  name: MySQL SLAVE DELAY ALERT
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{addon_id}}'
    level: Warning
    recover: "true"
- id: slave_sync_alert
  name: MySQL SLAVE SYNC ALERT
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{addon_id}}'
    level: Warning
    recover: "true"
- id: dice_addon_cassandra_gc_count
  name: 平台中间件Cassandra GC次数异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{addon_id}}'
    display_url_id: org_addon
    level: Warning
    recover: "true"
    tickets_metric_key: '{{addon_id}}'
- id: dice_addon_cassandra_gc_time
  name: 平台中间件Cassandra GC耗时异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{addon_id}}'
    display_url_id: org_addon
    level: Warning
    recover: "true"
    tickets_metric_key: '{{addon_id}}'
- id: dice_addon_container_cpu
  name: 平台中间件实例CPU状态
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    level: Warning
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: dice_addon_container_exit
  name: 平台中间件异常退出
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    display_url_id: org_pod
    level: Fatal
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: dice_addon_container_mem
  name: 平台中间件实例内存状态
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    level: Warning
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: dice_addon_container_ready
  name: 平台中间件实例Ready状态异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{daemonset_name}}-{{statefulset_name}}-{{deployment_name}}'
    level: Fatal
    recover: "true"
    tickets_metric_key: '{{daemonset_name}}-{{statefulset_name}}-{{deployment_name}}'
- id: dice_addon_elasticsearch_gc_count
  name: 平台中间件Elasticsearch GC次数异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{addon_id}}'
    display_url_id: org_addon
    level: Warning
    recover: "true"
    tickets_metric_key: '{{addon_id}}'
- id: dice_addon_elasticsearch_gc_time
  name: 平台中间件Elasticsearch GC耗时异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{addon_id}}'
    display_url_id: org_addon
    level: Warning
    recover: "true"
    tickets_metric_key: '{{addon_id}}'
- id: dice_addon_kafka_gc_count
  name: 平台中间件Kafka GC次数异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{addon_id}}'
    display_url_id: org_addon
    level: Warning
    recover: "true"
    tickets_metric_key: '{{addon_id}}'
- id: dice_addon_kafka_gc_time
  name: 平台中间件Kafka GC耗时异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{addon_id}}'
    display_url_id: org_addon
    level: Warning
    recover: "true"
    tickets_metric_key: '{{addon_id}}'
- id: dice_addon_kafka_lag
  name: 平台中间件kafka消费堆积
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{group}}-{{topic}}'
    display_url_id: org_addon
    level: Warning
    recover: "true"
    tickets_metric_key: '{{group}}-{{topic}}'
- id: dice_component_container_cpu
  name: 平台组件实例CPU状态
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    level: Warning
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: dice_component_container_exit
  name: 平台组件异常退出
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    display_url_id: org_pod
    level: Fatal
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: dice_component_container_mem
  name: 平台组件实例内存状态
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    level: Critical
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: dice_component_container_ready
  name: 平台组件实例Ready状态异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{daemonset_name}}-{{statefulset_name}}-{{deployment_name}}'
    level: Fatal
    recover: "true"
    tickets_metric_key: '{{daemonset_name}}-{{statefulset_name}}-{{deployment_name}}'
- id: dice_component_flink_checkpoint_duration
  name: 平台组件Flink任务checkpoint延迟异常告警
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}-{{job_id}}'
    level: Warning
    recover: "true"
    tickets_metric_key: '{{container_id}}-{{job_id}}'
- id: dice_component_flink_throughput
  name: 平台组件Flink吞吐量异常告警
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}-{{job_id}}'
    level: Warning
    recover: "true"
    tickets_metric_key: '{{container_id}}-{{job_id}}'
- id: dice_component_gfs_status
  name: 平台组件网盘不可用告警
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}'
    level: Fatal
    recover: "true"
    tickets_metric_key: '{{cluster_name}}'
- id: dice_component_log_protector
  name: 平台组价日志存储保护器状态变化
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}'
    level: Notice
    recover: "false"
    tickets_metric_key: '{{cluster_name}}'
- id: kubernetes_instance_cpu
  name: kubernetes组件实例CPU状态
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    level: Warning
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: kubernetes_instance_exit
  name: kubernetes组件异常退出
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    display_url_id: org_pod
    level: Fatal
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: kubernetes_instance_mem
  name: kubernetes组件实例内存状态
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    level: Critical
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: kubernetes_instance_ready
  name: kubernetes组件实例Ready状态异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{daemonset_name}}-{{statefulset_name}}-{{deployment_name}}'
    level: Fatal
    recover: "true"
    tickets_metric_key: '{{daemonset_name}}-{{statefulset_name}}-{{deployment_name}}'
- id: kubernetes_node
  name: kubernetes节点异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{node_name}}'
    level: Fatal
    recover: "true"
    tickets_metric_key: '{{node_name}}'
- id: machine_cluster_clock
  name: 机器时钟一致性异常告警
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{host_ip}}'
    display_url_id: machine_cluster_clock
    level: Warning
    recover: "true"
    tickets_metric_key: '{{host_ip}}'
- id: machine_cpu
  name: 机器CPU
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{host_ip}}'
    display_url_id: machine_cpu
    level: Warning
    recover: "true"
    tickets_metric_key: '{{host_ip}}'
- id: machine_disk
  name: 机器磁盘
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{host_ip}}-{{device}}'
    display_url_id: machine_disk
    level: Warning
    recover: "true"
    tickets_metric_key: '{{host_ip}}'
- id: machine_disk_inode
  name: 磁盘Inode异常告警
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{host_ip}}-{{device}}'
    display_url_id: machine_disk
    level: Warning
    recover: "true"
    tickets_metric_key: '{{host_ip}}'
- id: machine_disk_util
  name: 机器磁盘IO
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{host_ip}}'
    display_url_id: machine_disk_io
    level: Critical
    recover: "true"
    tickets_metric_key: '{{host_ip}}'
- id: machine_load5
  name: 机器Load5
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{host_ip}}'
    display_url_id: machine_load
    level: Warning
    recover: "true"
    tickets_metric_key: '{{host_ip}}'
- id: machine_netdisk
  name: 网盘
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}'
    level: Notice
    recover: "true"
    tickets_metric_key: '{{cluster_name}}'
- id: machine_netdisk_used
  name: 网盘容量使用量异常告警
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}'
    level: Fatal
    recover: "true"
    tickets_metric_key: '{{cluster_name}}'
- id: machine_status
  name: 机器宕机
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{host_ip}}'
    display_url_id: machine_crash
    level: Fatal
    recover: "true"
    tickets_metric_key: '{{host_ip}}'
- id: api_gateway_cpu
  name: API网关实例CPU使用率异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    level: Warning
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: api_gateway_mem
  name: API网关实例内存使用率异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    level: Warning
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: register_center_cpu
  name: 注册中心实例CPU使用率异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    level: Warning
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: register_center_mem
  name: 注册中心实例内存使用率异常
  alert_scope: org
  attributes:
    alert_group: '{{cluster_name}}-{{container_id}}'
    level: Warning
    recover: "true"
    tickets_metric_key: '{{container_id}}'
- id: sidecar_circuit_breaker
  name: 服务熔断通知告警
  alert_scope: micro_service
  attributes:
    alert_group: '{{terminus_key}}'
    level: Warning
    recover: "true"
    tickets_metric_key: '{{terminus_key}}'
